### ISSUE TITLE
Make check and Make deploy problems

### ISSUE THREAD

**Issue by Oboltusik** [meritlabs/merit#165]
### Describe the issue

Following the instructions (Mac OS X Build Instructions and Notes), I received errors when performing steps 3 and 4.

### Screenshots.
'make check' errors
![make_check_errors](https://user-images.githubusercontent.com/8020245/34469419-6779e5fe-ef2f-11e7-895d-c6b7ce761d7a.jpg)
'make deploy' errors
![make_deploy_errors](https://user-images.githubusercontent.com/8020245/34469420-6c5485d4-ef2f-11e7-8d56-8dcdce8583a6.jpg)

### What version of merit-core are you using?
0.1.0

### Machine specs:
- OS: MAC OS 10.11.6
- CPU: intel core 2 duo / 2GHz
- RAM: 4 GB 667 MHz DDR2 
- Disk size: 500 GB
- Disk Type (HD/SDD): HD

**Comment by adilwali** [comment]
@Oboltusik Thanks for opening this issue!  I suspect that this might be related to the QT wallet in Meritd, which is not yet ready for primetime. 

Meritd is CLI only at the moment, and our mobile apps are waiting for App store approval.  

So, with that in mind, give this a shot: 

- `make clean` 
- `./autogen.sh`
- `/configure --without-gui`
- `make`

The key is the *without-gui* flag in `./configure`

Please let us know if that works!

**Comment by Oboltusik** [comment]
@adilwali Nothing changed.

**Comment by adilwali** [comment]
@Oboltusik Sorry that this has been been a sticking point.  Are you able to simply run `make` instead of `make check` or `make deploy` for the moment?  We're working on a fix for the test-suite errors now.  In the meanwhile, you should be able to get the system to build so that you can run `./src/meritd`

Let me know!

**Comment by Oboltusik** [comment]
I just ran `make` and that's what I finally got: 

Making all in src
Making all in doc/man
make[1]: Nothing to be done for `all'.

make[1]: Nothing to be done for `all-am'.

Or you need more information?

**Comment by adilwali** [comment]
That looks like it might have worked, then!  Now you should be able to run:

`./src/meritd --conf=/path/to/your/merit.conf`

How does that go?

**Comment by Oboltusik** [comment]
Everything is working!
