### ISSUE TITLE
Merit Windows Wallet freezes if unlock is attempted during blockchain sync. 

### ISSUE THREAD

**Issue by adilwali** [meritlabs/merit#193]
## Context 
- Merit version 0.2.0 Windows x64
- Windows 10 - Version 1703 (Build15063.674)
- Intel Core iJ7-6700HQ CPU @ 2.60 GHZ.  
- 32 GB Ram

## Reproduction steps: 
1. Dismiss "Blockchain Syncing" overlay.
2. Enter unlock code and click submit.

## Behavior: 
- Blockchain synchronization stops, as evidenced by logs.
- Wallet UI stops responding, as seen below.

![screenshot 2](https://user-images.githubusercontent.com/192709/35198300-6f0d12b0-fea1-11e7-9096-cbcc6ceef549.png)

## Possible solutions:
- Do not let the user dismiss the blockchain synchronization screen.
- Do not let the user attempt the unlock until sync is complete. 
- Allow user to submit unlock code, but do not attempt to publish to blockchain until synchronization is complete.  (Eg, show a spinner, etc.)

**Comment by mempko** [comment]
Resolved , the user cannot dismiss the synchronization screen not beaconed.
