### ISSUE TITLE
Mining on mobile devices.

### ISSUE THREAD

**Issue by adilwali** [meritlabs/merit#205]
Merit aims to be the world's most adopted digital currency.  To that end, we've implemented a number of features that make it more accessible to non-technical-experts.  
 
_Ambassador mining_ is a pretty epic alternative to classic mining, and does not require a computer.  We should consider pushing further in this direction by making Merit mineable on mobile phones and other devices.   

This would do two things: 

- Allow people for whom sharing is not a good fit to participate in mining.  (People who are less social, have smaller networks, or perhaps less comfortable sharing Merit.)

- Allow people who are already ambassador mining, but do not own a computer, to participate in the _security mining_ as well. 

Cuckoo cycle lends itself well to this by being memory (and not CPU) bound.  

While, it stands to reason that phones probably will not be as competitive in security mining as PCs, people will still have a chance at winning the _security_ mining reward (whereas they wouldn't before.)  Further, every little bit helps as it pertains to securing the global network. 

**The big questions to consider are:**

- How effective will this be in the somewhat sandboxed iOS ecosystem?
- How much, if any, code can be re-used across iOS and android?
- Would we have to drop Ionic entirely for the LightWallet to do this?
- Should this be a separate application, entirely?  (A 1-click miner, perhaps?)

**Comment by eugene-sy** [comment]
It does not make sense anymore as Apple and Google banned mining apps in their application stores.
