### ISSUE TITLE
When rebooting mining should be enabled if it was enabled prior

### ISSUE THREAD

**Issue by scottrutherford** [meritlabs/merit#259]
This issue tracker is only for technical issues related to merit-core.

General Merit questions and/or support requests and are best directed to our support or community sites.

For reporting security issues, please read [instructions](#).

### Describe the issue
After rebooting mining is disabled

#### If so, please list the steps to reproduce below:
1. Enable mining
2. Reboot
3. Mining is no longer enabled

### Expected behaviour
Mining should be enabled

### Actual behaviour
Mining is disabled

**Comment by Axblade** [comment]
@scottrutherford are we talking about Desktop application now?
With the daemon, you could use `-mine` parameter when you launch `meritd`, like this:
```
meritd -mine
```

**Comment by mempko** [comment]
This should be working as described now.
