### ISSUE TITLE
Ability to cancel invitation request

### ISSUE THREAD

**Issue by adilwali** [meritlabs/merit#261]
Originally from _AkiAfroo_ on Discord.

It would be nice to cancel invitation requests.  Probably, the best way to do this would be swap out the existing invitation request with a new a new one (requesting an invite to someone else).

Considerations:
* We don't want people to spam lots of different people for invites.

**Comment by mempko** [comment]
Resolved by #295

**Comment by Akiafroo** [comment]
i love it! thanks guys for made it possible!
