### ISSUE TITLE
Unlock wallet when beacon is mined on full merit node.  (CLI)

### ISSUE THREAD

**Issue by tonypizzicato** [meritlabs/merit#27]
## Wallet unlock flow

1. wallet is locked when created. No key pairs are generated (keypool is empty)
2. `unlockwallet` is called with bare referral code(short (?) string that is shared publicly)
3. one key pair is generated alongside with referral code associated with pubkey generated. beacon transaction is sent to the network
4. beacon transaction propagates through the network and gets to referral mempool on all nodes
5. transaction got mined in the next (or not) block
6. mined block is propagated through the network
7. local node gets new block when mined and looks  for its own beacon transactions
8. if found in the block(confirmed) it unlocks the wallet and generates all other key pairs for the keypool (`TopUpKeyPool`) with associated referrals and sends beacon transactions for these keys
9. if not found goto `6.`

## Tasks
1. Disable keypool creation on startup
2. Add `unlockwallet` rpc method and `CWallet::Unlock(std::string codeIn)` method, that generates keypair, referral with provided code and new pubkey, send beacon transaction to the network
3. Add processing of network messages - check for beacon transaction in new blocks when mined and the same while downloading blockchain and lookup for wallet's transactions and save them to local database and unlock the wallet if first beacon transaction if found

**Comment by Axblade** [comment]
@tonypizzicato @adilwali shall we close this issue?

**Comment by mempko** [comment]
This has been resolved a while ago.
