### ISSUE TITLE
User should be able to reject or hide invite requests. 

### ISSUE THREAD

**Issue by adilwali** [meritlabs/merit#286]
Users should be able to reject or cancel incoming invitation requests in the desktop wallet.  

This button could be called: 
* Ignore
* Hide
* Reject

If this is not an explicit rejection, then the user should be able to, eventually, see a list of their hidden requests.  This way, if they change their minds, they will have the opportunity to send the invite to someone they previously ignored.  

See the screenshot below that considers where it might be positioned: 
<img width="948" alt="merit_core_-_wallet" src="https://user-images.githubusercontent.com/192709/37416750-dc64e0e8-276b-11e8-8a7c-93a17e5fd790.png">

**Comment by mempko** [comment]
Added in #295
