### ISSUE TITLE
Invites cannot be sent from UI of encrypted wallets

### ISSUE THREAD

**Issue by Axblade** [meritlabs/merit#302]
### Steps to reproduce

* Encrypt the wallet, and restart the application  
* Send an invitation request to the address of the encrypted wallet
* Try approving the request

Result: a user gets a message like `There was an error inviting Someone with the address XXXX`. Also, there is nothing in logs related to the issue.

Expected behavior: a user sees a prompt to enter her passphrase to unlock the encrypted wallet.

### Workaround

A user can go to debug window, open console and enter: `inviteaddress XXXX`, the error about encrypted wallet is shown.
If a user unlocks her wallet and then tries to invite XXXX, the transaction is accepted.

### What's needed to be done
- [ ] Improve UX: show the prompt to enter a passphrase to unlock the wallet
- [ ] Add more meaningful error message text in case an error happens
- [ ] Add log messages if an error happens during invite transaction creation process

**Comment by mempko** [comment]
Resolved in #288
