### ISSUE TITLE
Windows version reindexes after closing merit right after being invited.

### ISSUE THREAD

**Issue by mempko** [meritlabs/merit#327]
### Describe the issue

New users on Windows have to reindex if they close merit within 5 minutes of being invited.

Error in log

`[0%]...[16%]...[25%]...[33%]...[41%]...ERROR: UndoReadFromDisk: Checksum mismatch`

### Can you reliably reproduce the issue?

Close merit within 5 minutes of being invited.

### Expected behaviour
Restarting should not require reindexing.

### Actual behaviour
Checksum in undo file fails and forces a reindex.

### What version of merit-core are you using?
Windows 0.4.4

**Comment by Axblade** [comment]
It's fixed, isn't it? @mempko

**Comment by mempko** [comment]
@Axblade Yes, this is fixed!
