### ISSUE TITLE
Mining Indicator on Desktop App

### ISSUE THREAD

**Issue by jessicakwalters** [meritlabs/merit#331]
### Describe the issue

When I look at the Merit Desktop app I can't immediately tell if I'm mining or not. 

#### If so, please list the steps to reproduce below:
1. Open or navigate to the desktop app
2. Review app screen
3. Without checking the menu, it's not possible to tell if you're actively mining. 

### Preferred behaviour
When I open or navigate to the app, I should see some indicator (icon, status, etc.) that clearly shows if I'm actively mining or not.

**Comment by Axblade** [comment]
Thank you for the report. This part of the app can be improved.
There is a small indicator in the bottom status bar, but it can be hard to notice:

<img width="179" alt="screenshot 2018-04-17 21 12 14" src="https://user-images.githubusercontent.com/771978/38888491-74b59044-4284-11e8-8fa3-c98c7c1565c3.png">

<img width="201" alt="screenshot 2018-04-17 21 12 02" src="https://user-images.githubusercontent.com/771978/38888492-7658c3b2-4284-11e8-892d-bc112bcd8f94.png">
