### ISSUE TITLE
Wallet passphrase must be entered in order to run `merit-cli help`

### ISSUE THREAD

**Issue by adilwali** [meritlabs/merit#337]
Today, if you run the `merit-cli help` command on an encrypted wallet, you will see an error that prompts you to enter a wallet passphrase first.

This is not ideal, unless there is an important reason (that I can't think of) that the user would be need to have unlocked their wallet to see the help command output.

**Comment by mempko** [comment]
Fixed here: https://github.com/meritlabs/merit/commit/f9851611267a7a413173694f9781d638096389d9
