### ISSUE TITLE
Ambassador Rewards show as Mining Rewards in Web Wallet

### ISSUE THREAD

**Issue by mrtakens** [meritlabs/merit#356]
### Describe the issue
Ambassador Rewards show as Mining Rewards in Web Wallet

#### Please list the steps to reproduce below:
1. Achieve an Ambassador Reward
2. Look at History tab in the Web Wallet

### Expected behaviour
The title of the transaction should be Ambassador Reward (like on the Desktop App)

### Actual behaviour
The title of the transaction is Mining Reward

### Screenshots.
<img width="938" alt="screen shot 2018-05-18 at 3 50 23 pm" src="https://user-images.githubusercontent.com/27923521/40257647-912c65ca-5ab4-11e8-90a9-20c85853f441.png">

**Comment by adilwali** [comment]
This is great feedback, and makes total sense. 

We are planning to rename "Ambassador Mining" to "Growth Mining" and re-labelling these rewards should be part of that.

**Comment by eugene-sy** [comment]
It's an LW issue and should be resolved by now.
