### ISSUE TITLE
Receiving Multiple Email Notifications for Same Reward

### ISSUE THREAD

**Issue by mrtakens** [meritlabs/merit#361]
### Describe the issue
After adding my email address for notifications, I get 3-4 of the same email when earning an ambassador reward.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Add email to web wallet for notifications
2. Earn Ambassador Reward

### Expected behaviour
Receive one email for reward

### Actual behaviour
Receive multiple emails for one reward

### Screenshots.
![3c22bb07-78ce-4fba-88e9-f05431e238fb](https://user-images.githubusercontent.com/27923521/40877901-ce99b530-664d-11e8-8ad8-745558d7352d.png)

**Comment by eugene-sy** [comment]
It's an LW issue and should be resolved by now.
