### ISSUE TITLE
All links should be open in the same way from one page [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#369]
### Test Steps
1. Open https://wallet.merit.me/onboarding/tour-beginners
2. Click on link "controlled-growth and growth mining"
3. Go back
4. Click on "Visit site" or  "Join the Conversation"

--

### Expected behaviour
All links opened in a new tab.

### Actual behaviour
Link "controlled-growth and growth mining" opened in the same tab, links "Visit site" and "Join the Conversation" opened in new tab.

### Screenshots.
https://gyazo.com/b267d21485ee993ca7bd444ed96a1a2e

**Comment by eugene-sy** [comment]
Copied to the LW repo
