### ISSUE TITLE
With a window width of less than 890px, the pop-up message is not completely displayed [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#370]
### Test Steps
1. Go to https://wallet.merit.me/onboarding/unlock
2. Reduce browser window width < 890 px
3. Type 1 on invite code field

### Expected behaviour
The pop-up message completely displayed

### Actual behaviour
The pop-up message is not completely displayed

### Screenshots
![d26f196b4ba1080142bc12db253a4f9b](https://user-images.githubusercontent.com/40575121/41921176-f646e672-796a-11e8-8357-d27b5dbfadcd.png)

**Comment by achevgun** [comment]
Also on some pages there is an overlay of icons

![image](https://user-images.githubusercontent.com/40575121/41923661-ae16c39e-7970-11e8-8db1-136f9ca56934.png)

**Comment by eugene-sy** [comment]
Linked to LW
