### ISSUE TITLE
It is possible to enter aliace with spaces [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#371]
There should be no "Next" button until the alias is entered correctly, according to the rules:
*Allowed characters: Numbers/letters only. No Spaces. 
*Max length: 20 characters

### Test Steps
1. Go to https://wallet.merit.me/onboarding/unlock
2. Enter an invite code. For example 123
3.  Enter an alias with spaces
4. Click "Next"

### Expected behaviour
Invalid alias format.  "Next" button is unavailable.

### Actual behaviour
The Next button is available

### Screenshots.
![image](https://user-images.githubusercontent.com/40575121/41922597-242e20ac-796e-11e8-8114-2e43e1612393.png)

**Comment by eugene-sy** [comment]
copied to LW
