### ISSUE TITLE
Empty page after click on "Go back" [onboarding/unlock] [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#372]
### Test Steps
1. Go to https://wallet.merit.me/onboarding/unlock
2. Enter an invite code. For example 123
3. Enter an new valid alias
4. Click "Next"
5. Click "Go Back"

### Expected behaviour
The page with the data entered in the previous step is opened

### Actual behaviour
The page is empty

### Screenshots.
https://gyazo.com/9ba2cd08bdd3a3b2d1fae591fc37283a

**Comment by eugene-sy** [comment]
copied to LW
