### ISSUE TITLE
Lock screen doesn't lock screen fully [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#373]
### Precondition
- The height of the browser window is not more than 850px

### Test Steps
1. Create new wallet or log in wiht locked wallet
2. Go to https://wallet.merit.me/send
3. Scroll down

### Expected behaviour
Lock-screen locks screen fully

### Actual behaviour
Lock-screen doesn't lock screen fully

### Screenshots
https://gyazo.com/90e3198bca831b95251fbf78cc0659a6

**Comment by eugene-sy** [comment]
copied to LW
