### ISSUE TITLE
There is no validation of email in the settings[DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#374]
### Precondition
- User is authorized at https://wallet.merit.me

### Test Steps
1. Go to https://wallet.merit.me/settings
2. Enable Email notifications
3. Enter invalid Email address

### Expected behaviour
Message: Invalid Email format.

### Actual behaviour
Success. User subscribed to Email nottifications.

### Screenshots
![image](https://user-images.githubusercontent.com/40575121/41925238-b55a969a-7974-11e8-8855-32b72c43fecd.png)

**Comment by eugene-sy** [comment]
copied to LW
