### ISSUE TITLE
There is no validation on Phone number in the settings [DLW]

### ISSUE THREAD

**Issue by achevgun** [meritlabs/merit#375]
### Precondition
- User is authorized at https://wallet.merit.me

### Test Steps
1. Go to https://wallet.merit.me/settings
2. Enable Enable SMS notifications
3. Enter 10 digits and any symbols on Phone number field. Example: 1234567890FGD%$^^g

### Expected behaviour
Message: Invalid Phone number format.

### Actual behaviour
Success. User subscribed to SMS nottifications.

### Screenshots
![image](https://user-images.githubusercontent.com/40575121/41926506-39936b3c-7978-11e8-9657-d18e08ab6403.png)

**Comment by eugene-sy** [comment]
copied to LW
