### ISSUE TITLE
Assert in refdb.cpp:323: bool referral::ReferralsViewDB::UpdateANV

### ISSUE THREAD

**Issue by daves0** [meritlabs/merit#386]
### Describe the issue
Merit crashes with an assert immediately after loading blocks, when it begins verifying.

#### If so, please list the steps to reproduce below:
1. Happens every time I run Merit, qt or daemon, Linux or Windows
2. Asserts immediately when starting to verify blocks after load
3.

### Expected behaviour
Tell us what should happen
It should verify blocks

### Actual behaviour
Tell us what happens instead
It asserts:  
merit-qt: refdb.cpp:323: bool referral::ReferralsViewDB::UpdateANV(char, const Address&, CAmount): Assertion `anv_in.first >= 0' failed.
Aborted (core dumped)

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of merit-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
latest merit self-compiled via git pull from this repo on Linux and downloaded Windows installer, all v0.5.5.0-df2e6dc

### Machine specs:
- OS: Ubuntu 18.04, Windows 7, Ubuntu 16.04
- CPU: AMD Athlon, Intel i7 ( yes, my Athlon is a miner :P )
- RAM: 4GB - 16GB
- Disk size: - 500M - 1TB
- Disk Type (HD/SDD): HD and SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

I am using Ubuntu's Berkely db, not the standard one for merit as defined in the build instructions.  Dunno if that makes a difference or not.  The file db.log is empty, and debug.log has no entries in it since 7/17.  Let me know if there's any further info I can provide.

**Comment by daves0** [comment]
Just updated via git pull from this repo to 

Merit Core RPC client version v0.5.5.0-f891473

and am still having the same issue.

**Comment by mempko** [comment]
Try running 

merit-cli reconsiderblock 18dc863dbd74d07ad41a6b09e80cf314c8e5db23a80d0b0d46774486dad19178

**Comment by mempko** [comment]
This issue was fixed with 0.5.5. Running the command above should solve the problem. Please reopen if it doesn't work for you.

**Comment by daves0** [comment]
I can't run the merit-cli command because the server won't run.  It dies before verifying blocks, and merit-cli has no server to attach to.
